[package]
name = "ecma-lalrpop"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }

[dependencies]
lalrpop-util = { version = "0.19.1", features = ["lexer"] }
